### ISSUE TITLE
Doesn't work with enterprise github

### ISSUE THREAD

**Issue by bigH** [sqren/github-widescreen#2]
Many organizations use github. It'd be nice to be able to support this plugin for privately deployed github by using URL patterns.

**Comment by aaron-mcdaid-zalando** [comment]
With a little hack, I managed to make this easily work with Github Enterprise:

1.  clone this repo to your local machine
1.  Modify the `manifest.json` file in this repo to add an extra entry to the `matches` field: e.g. something like `"matches": ["https://*.github.com/*", "https://your.internal.github.website.intranet/*"],`
1.  Visit chrome://extensions/
1.  (Remove the extension if you already have it installed)
1.  Enable 'Developer Mode' in the very top right of that page
2.  Click 'Load unpacked' in the top left and point it at your local directory containing this edit

**Comment by aaronmcdaid** [comment]
With a little hack, I managed to make this easily work with Github Enterprise:

1.  clone this repo to your local machine
1.  Modify the `manifest.json` file in this repo to add an extra entry to the `matches` field: e.g. something like
````"matches": ["https://*.github.com/*", "https://your.internal.github.website.intranet/*"],````
1.  Visit chrome://extensions/
1.  (Remove the extension if you already have it installed)
1.  Enable 'Developer Mode' in the very top right of that page
2.  Click 'Load unpacked' in the top left and point it at your local directory containing this edit

**Comment by luke-lan** [comment]
This solution worked perfectly, thanks for the heads up @aaronmcdaid!

**Comment by GuyKh** [comment]
Worked for me too, but this is somewhat of a hack.
It'll be much better if you could add a Options page where you could add a 'custom GitHub URLs' so you could use the original addon

**Comment by huyz** [comment]
It might be a good idea to keep this issue open until custom URLs can be added to the extension.
