### ISSUE TITLE
Comment buttons are not visible in wide diff

### ISSUE THREAD

**Issue by dinoboy197** [sqren/github-widescreen#7]
I'm using version 0.7.2.

![image](https://user-images.githubusercontent.com/631178/50602153-a20b3600-0e5a-11e9-8806-6ee1a0a87173.png)

Scrolling to the right does not make the buttons appear.

**Comment by sqren** [comment]
Hi @dinoboy197 
Thanks for letting me know about this. Unfortunately I am not able to reproduce. 

If I activate wide screen on this URL https://github.com/sqren/github-widescreen/commit/24225613864ca2cfce131de37a812875dae2446d#diff-04c6e90faac2675aa89e2176d2eec7d8R4 I still see the button

<img width="1503" alt="screenshot 2019-01-02 at 21 58 15" src="https://user-images.githubusercontent.com/209966/50612293-c9551800-0ed9-11e9-9a03-151f410c177b.png">

Do you also see the button on the above url or is it also broken for you?

**Comment by dinoboy197** [comment]
Thanks for your quick reply. I had expected the comment box to show up with a horizontal scrollbar, but it turns out that I have to scroll vertically to the bottom of the file that is being commented on to access the horizontal scroll. When I use this horizontal scroll at the bottom, then scroll back up, the comment button does appear.
